name: Test
on:
  push:
    branches:
      - master
jobs:
  check-code:
    name: Check code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install nix
      uses: cachix/install-nix-action@v24
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check code
      run: |
        nix-shell --command "just check"
